T = {
"   Ouvrir developer.spotify.com/dashboard": ("   Open developer.spotify.com/dashboard", "   Открыть developer.spotify.com/dashboard", "   developer.spotify.com/dashboard öffnen"),
"   Ouvrir la page Developers de Discogs": ("   Open the Discogs Developers page", "   Открыть страницу Developers на Discogs", "   Discogs-Seite „Developers“ öffnen"),
"   Ouvrir platform.claude.com": ("   Open platform.claude.com", "   Открыть platform.claude.com", "   platform.claude.com öffnen"),
"%@ (absente)": ("%@ (missing)", "%@ (нет на Mac)", "%@ (fehlt)"),
"%@ / %@ · FACE %@": ("%@ / %@ · SIDE %@", "%@ / %@ · СТОРОНА %@", "%@ / %@ · SEITE %@"),
"%@ DE MUSIQUE": ("%@ OF MUSIC", "%@ МУЗЫКИ", "%@ MUSIK"),
"%@ LIBRES": ("%@ FREE", "%@ СВОБОДНО", "%@ FREI"),
"%@ · %lld titres": ("%@ · %lld tracks", "%@ · треков: %lld", "%@ · %lld Titel"),
"%lld TITRES": ("%lld TRACKS", "ТРЕКОВ: %lld", "%lld TITEL"),
"%lld cassette · prochain numéro : %@": ("%lld tape · next number: %@", "Кассет: %lld · следующий номер: %@", "%lld Kassette · nächste Nummer: %@"),
"%lld cassettes · prochain numéro : %@": ("%lld tapes · next number: %@", "Кассет: %lld · следующий номер: %@", "%lld Kassetten · nächste Nummer: %@"),
"%lld format coché · papier 170 à 250 g/m² · étiquettes sur papier autocollant": ("%lld format selected · 170–250 g/m² paper · labels on adhesive paper", "Выбрано форматов: %lld · бумага 170–250 г/м² · этикетки на самоклеящейся бумаге", "%lld Format gewählt · Papier 170–250 g/m² · Etiketten auf Klebepapier"),
"%lld formats cochés · papier 170 à 250 g/m² · étiquettes sur papier autocollant": ("%lld formats selected · 170–250 g/m² paper · labels on adhesive paper", "Выбрано форматов: %lld · бумага 170–250 г/м² · этикетки на самоклеящейся бумаге", "%lld Formate gewählt · Papier 170–250 g/m² · Etiketten auf Klebepapier"),
"%lld min/face": ("%lld min/side", "%lld мин/сторона", "%lld Min./Seite"),
"(une règle de 10 cm et une de 4 pouces)": ("(a 10 cm ruler and a 4-inch ruler)", "(линейка 10 см и линейка 4 дюйма)", "(ein 10-cm- und ein 4-Zoll-Lineal)"),
"1. Clé API Claude": ("1. Claude API key", "1. Ключ API Claude", "1. Claude-API-Schlüssel"),
"1. Colle le Client ID dans STUDIOLAFLEUR, puis clique « Se connecter… ».": ("1. Paste the Client ID into STUDIOLAFLEUR, then click “Connect…”.", "1. Вставь Client ID в STUDIOLAFLEUR и нажми «Подключиться…».", "1. Füge die Client ID in STUDIOLAFLEUR ein und klicke auf „Verbinden…“."),
"1. Compte à rebours %lld s : relâche la pause": ("1. %lld s countdown: release pause", "1. Обратный отсчёт %lld с: отпусти паузу", "1. %lld s Countdown: Pause lösen"),
"1. Connecte-toi sur discogs.com (compte gratuit).": ("1. Log in at discogs.com (free account).", "1. Войди на discogs.com (бесплатный аккаунт).", "1. Melde dich bei discogs.com an (kostenloses Konto)."),
"1. Créer l'appli Spotify (une seule fois)": ("1. Create the Spotify app (once)", "1. Создай приложение Spotify (один раз)", "1. Spotify-App anlegen (einmalig)"),
"1. Va sur developer.spotify.com et connecte-toi avec ton compte Spotify.": ("1. Go to developer.spotify.com and log in with your Spotify account.", "1. Зайди на developer.spotify.com и войди со своим аккаунтом Spotify.", "1. Geh auf developer.spotify.com und melde dich mit deinem Spotify-Konto an."),
"1. Va sur platform.claude.com et connecte-toi (ou crée un compte).": ("1. Go to platform.claude.com and log in (or create an account).", "1. Зайди на platform.claude.com и войди (или создай аккаунт).", "1. Geh auf platform.claude.com und melde dich an (oder erstelle ein Konto)."),
"2. Accepte les conditions des développeurs si Spotify te les montre.": ("2. Accept the developer terms if Spotify shows them.", "2. Прими условия для разработчиков, если Spotify их покажет.", "2. Akzeptiere die Entwicklerbedingungen, falls Spotify sie anzeigt."),
"2. Ajoute un peu de crédit : Settings → Billing (quelques francs suffisent pour beaucoup de cassettes).": ("2. Add some credit: Settings → Billing (a few dollars cover many tapes).", "2. Пополни баланс: Settings → Billing (пары долларов хватит на много кассет).", "2. Lade etwas Guthaben auf: Settings → Billing (ein paar Franken reichen für viele Kassetten)."),
"2. Blanc de début : %lld s": ("2. Leader silence: %lld s", "2. Тишина в начале: %lld с", "2. Stille am Anfang: %lld s"),
"2. Je mesure en": ("2. I measure in", "2. Измеряю в", "2. Ich messe in"),
"2. Se connecter depuis STUDIOLAFLEUR": ("2. Connect from STUDIOLAFLEUR", "2. Подключение из STUDIOLAFLEUR", "2. Aus STUDIOLAFLEUR verbinden"),
"2. Settings → Developers → « Generate new token ».": ("2. Settings → Developers → “Generate new token”.", "2. Settings → Developers → «Generate new token».", "2. Settings → Developers → „Generate new token“."),
"2. Spotify (facultatif, Premium obligatoire)": ("2. Spotify (optional, Premium required)", "2. Spotify (необязательно, нужен Premium)", "2. Spotify (optional, Premium nötig)"),
"2. Ton navigateur ouvre une page Spotify qui demande l'accès à tes playlists : clique « Agree » (Accepter).": ("2. Your browser opens a Spotify page asking for access to your playlists: click “Agree”.", "2. Браузер откроет страницу Spotify с запросом доступа к плейлистам: нажми «Agree».", "2. Dein Browser öffnet eine Spotify-Seite, die Zugriff auf deine Playlists möchte: klicke „Agree“."),
"3. Clique « Create app ». Nom : STUDIOLAFLEUR. Description : ce que tu veux.": ("3. Click “Create app”. Name: STUDIOLAFLEUR. Description: anything you like.", "3. Нажми «Create app». Имя: STUDIOLAFLEUR. Описание: любое.", "3. Klicke „Create app“. Name: STUDIOLAFLEUR. Beschreibung: beliebig."),
"3. Copie le jeton ici. Il est rangé dans le trousseau du Mac.": ("3. Paste the token here. It is stored in the Mac keychain.", "3. Вставь токен сюда. Он хранится в связке ключей Mac.", "3. Füge das Token hier ein. Es wird im Schlüsselbund des Mac gespeichert."),
"3. Dossier audio": ("3. Audio folder", "3. Папка с аудио", "3. Audio-Ordner"),
"3. La page affiche « C'est bon, Spotify est connecté », et STUDIOLAFLEUR « Connecté ✓ ». Tu peux fermer l'onglet.": ("3. The page says “Spotify is connected” and STUDIOLAFLEUR shows “Connected ✓”. You can close the tab.", "3. Страница покажет «Spotify подключён», а STUDIOLAFLEUR — «Подключено ✓». Вкладку можно закрыть.", "3. Die Seite zeigt „Spotify ist verbunden“ und STUDIOLAFLEUR „Verbunden ✓“. Du kannst den Tab schließen."),
"3. La règle de %@ mesure :": ("3. The %@ ruler measures:", "3. Линейка %@ имеет длину:", "3. Das %@-Lineal misst:"),
"3. Les morceaux, %lld s de blanc entre chacun": ("3. The tracks, %lld s of silence between each", "3. Треки, %lld с тишины между ними", "3. Die Titel, %lld s Stille dazwischen"),
"3. Settings → API keys → Create key. Donne-lui un nom (« STUDIOLAFLEUR »), garde le workspace « Default ».": ("3. Settings → API keys → Create key. Name it (“STUDIOLAFLEUR”), keep the “Default” workspace.", "3. Settings → API keys → Create key. Дай имя («STUDIOLAFLEUR»), оставь workspace «Default».", "3. Settings → API keys → Create key. Gib einen Namen („STUDIOLAFLEUR“), behalte den Workspace „Default“."),
"4. Arrêt net à la fin de la face": ("4. Clean stop at the end of the side", "4. Чёткая остановка в конце стороны", "4. Sauberer Stopp am Seitenende"),
"4. Copie la clé qui commence par sk-ant-. Elle ne s'affiche qu'une seule fois : si tu la perds, crée-en une autre.": ("4. Copy the key starting with sk-ant-. It is shown only once: if you lose it, create another.", "4. Скопируй ключ, начинающийся с sk-ant-. Он показывается один раз: если потеряешь, создай новый.", "4. Kopiere den Schlüssel, der mit sk-ant- beginnt. Er wird nur einmal angezeigt: Verlierst du ihn, erstelle einen neuen."),
"4. Redirect URI : copie exactement l'adresse ci-dessous, puis clique « Add » :": ("4. Redirect URI: copy the address below exactly, then click “Add”:", "4. Redirect URI: скопируй адрес ниже точно и нажми «Add»:", "4. Redirect URI: kopiere die Adresse unten exakt und klicke „Add“:"),
"4. Sortie vers la platine": ("4. Output to the deck", "4. Выход на деку", "4. Ausgang zum Tapedeck"),
"5. Colle-la uniquement ici, dans STUDIOLAFLEUR, puis clique « Tester » : « OK » s'affiche.": ("5. Paste it only here, in STUDIOLAFLEUR, then click “Test”: “OK” appears.", "5. Вставь его только сюда, в STUDIOLAFLEUR, и нажми «Проверить»: появится «OK».", "5. Füge ihn nur hier in STUDIOLAFLEUR ein und klicke „Testen“: „OK“ erscheint."),
"5. Conditions d'utilisation": ("5. Terms of use", "5. Условия использования", "5. Nutzungsbedingungen"),
"5. Dans « Which API/SDKs are you planning to use? », coche « Web API ». Accepte et clique « Save ».": ("5. Under “Which API/SDKs are you planning to use?”, tick “Web API”. Accept and click “Save”.", "5. В «Which API/SDKs are you planning to use?» отметь «Web API». Прими и нажми «Save».", "5. Bei „Which API/SDKs are you planning to use?“ „Web API“ ankreuzen. Akzeptieren und „Save“ klicken."),
"5. Fin de bande, inversion, face B automatique": ("5. End of tape, reverse, side B automatically", "5. Конец ленты, реверс, сторона B автоматически", "5. Bandende, Umkehr, Seite B automatisch"),
"5. « Retourne la cassette »": ("5. “Flip the tape”", "5. «Переверни кассету»", "5. „Kassette umdrehen“"),
"6. Ouvre l'appli → Settings : copie le « Client ID ». Ne prends pas le « Client secret », l'app n'en a pas besoin.": ("6. Open the app → Settings: copy the “Client ID”. Don't take the “Client secret”, the app doesn't need it.", "6. Открой приложение → Settings: скопируй «Client ID». «Client secret» не нужен.", "6. Öffne die App → Settings: kopiere die „Client ID“. Das „Client secret“ brauchst du nicht."),
"Accent": ("Accent", "Акцент", "Akzent"),
"Actions": ("Actions", "Действия", "Aktionen"),
"Actualiser": ("Refresh", "Обновить", "Aktualisieren"),
"Aide sur la clé API Claude": ("Help with the Claude API key", "Помощь с ключом API Claude", "Hilfe zum Claude-API-Schlüssel"),
"Ajouter la sélection": ("Add selection", "Добавить выбранное", "Auswahl hinzufügen"),
"Ajuster": ("Fit", "Вписать", "Einpassen"),
"Album": ("Album", "Альбом", "Album"),
"Album, playlist ou lien": ("Album, playlist or link", "Альбом, плейлист или ссылка", "Album, Playlist oder Link"),
"Album, ou « Artiste - Album »…": ("Album, or “Artist - Album”…", "Альбом или «Исполнитель - Альбом»…", "Album oder „Künstler - Album“…"),
"Ambiance": ("Mood", "Настроение", "Stimmung"),
"Annuler": ("Cancel", "Отмена", "Abbrechen"),
"Aperçu 3D": ("3D preview", "3D-просмотр", "3D-Vorschau"),
"Appliquer les corrections de Claude": ("Apply Claude's fixes", "Применить исправления Claude", "Korrekturen von Claude übernehmen"),
"Artiste": ("Artist", "Исполнитель", "Künstler"),
"Attention : l'abonnement Claude (Pro ou Max) ne donne pas de clé API. L'API est un compte à part, payé à l'usage.": ("Note: a Claude subscription (Pro or Max) does not include an API key. The API is a separate, pay-as-you-go account.", "Внимание: подписка Claude (Pro или Max) не даёт ключ API. API — отдельный аккаунт с оплатой по факту.", "Achtung: Ein Claude-Abo (Pro oder Max) enthält keinen API-Schlüssel. Die API ist ein eigenes Konto mit Abrechnung nach Nutzung."),
"Aucun fichier audio associé : ce morceau ne peut pas être enregistré. Choisis ton dossier audio à gauche.": ("No audio file linked: this track can't be recorded. Choose your audio folder on the left.", "Нет аудиофайла: этот трек нельзя записать. Выбери папку с аудио слева.", "Keine Audiodatei zugeordnet: Dieser Titel kann nicht aufgenommen werden. Wähle links deinen Audio-Ordner."),
"Auto": ("Auto", "Авто", "Auto"),
"Auto-reverse": ("Auto-reverse", "Автореверс", "Auto-Reverse"),
"Auto-reverse : la platine se retourne toute seule": ("Auto-reverse: the deck flips by itself", "Автореверс: дека переворачивает сама", "Auto-Reverse: das Deck wendet selbst"),
"Autres idées": ("More ideas", "Другие идеи", "Weitere Ideen"),
"Avant de commencer": ("Before you start", "Перед началом", "Bevor du anfängst"),
"Avant de lancer": ("Before starting", "Перед запуском", "Vor dem Start"),
"Avec %lld volets, une partie va au verso : impression recto verso. Ajoute des volets pour tout imprimer d'un côté.": ("With %lld panels, part goes on the back: double-sided printing. Add panels to print everything on one side.", "При %lld панелях часть уходит на оборот: двусторонняя печать. Добавь панели, чтобы всё было на одной стороне.", "Mit %lld Feldern kommt ein Teil auf die Rückseite: beidseitiger Druck. Füge Felder hinzu, um alles einseitig zu drucken."),
"Baisse les morceaux les plus forts au niveau du plus calme. Désactivé : chaque fichier est joué tel quel.": ("Lowers the loudest tracks to the quietest one. Off: each file plays as is.", "Приглушает самые громкие треки до уровня самого тихого. Выключено: каждый файл играет как есть.", "Senkt die lautesten Titel auf den leisesten. Aus: jede Datei spielt unverändert."),
"Bande": ("Tape", "Лента", "Band"),
"Bande rembobinée": ("Tape rewound", "Лента перемотана", "Band zurückgespult"),
"Bande utilisée": ("Tape used", "Использовано ленты", "Verwendetes Band"),
"Barres": ("Barcode", "Штрихкод", "Strichcode"),
"Bientôt": ("Soon", "Скоро", "Bald"),
"Bord gauche → trait rouge :": ("Left edge → red line:", "Левый край → красная линия:", "Linker Rand → rote Linie:"),
"Bord haut → trait rouge :": ("Top edge → red line:", "Верхний край → красная линия:", "Oberer Rand → rote Linie:"),
"Brouillon": ("Draft", "Черновик", "Entwurf"),
}
