# Demandes 1 à 8 : éléments réglables, codes en mm, étiquettes, IA expert, historique, boîte « Modifier avec l'IA ».
T = {
"%@ modifie la cassette…": ("%@ is editing the cassette…", "%@ меняет кассету…", "%@ bearbeitet die Kassette…"),
"%@ n'a rien changé": ("%@ changed nothing", "%@ ничего не изменил", "%@ hat nichts geändert"),
"%@ pt": ("%@ pt", "%@ pt", "%@ pt"),
"%@ × %@ mm": ("%@ × %@ mm", "%@ × %@ мм", "%@ × %@ mm"),
"%lld changement(s) appliqué(s) ✓": ("%lld change(s) applied ✓", "Изменений применено: %lld ✓", "%lld Änderung(en) übernommen ✓"),
"%lld demandes": ("%lld requests", "Запросов: %lld", "%lld Anfragen"),
"%lld demandes · environ %@ $": ("%lld requests · about $%@", "Запросов: %lld · около %@ $", "%lld Anfragen · etwa %@ $"),
"Afficher les demandes faites à l'IA": ("Show the requests made to the AI", "Показать запросы к ИИ", "Anfragen an die KI anzeigen"),
"Annuler la dernière modification (⌘Z)": ("Undo the last change (⌘Z)", "Отменить последнее изменение (⌘Z)", "Letzte Änderung rückgängig machen (⌘Z)"),
"Annulé": ("Undone", "Отменено", "Rückgängig gemacht"),
"Appliquer": ("Apply", "Применить", "Anwenden"),
"Appliquer (⌘↩)": ("Apply (⌘↩)", "Применить (⌘↩)", "Anwenden (⌘↩)"),
"Aucune demande à l'IA pour cette cassette.": ("No AI requests for this cassette yet.", "Для этой кассеты запросов к ИИ нет.", "Noch keine KI-Anfragen für diese Kassette."),
"Cassette %@ ouverte": ("Cassette %@ opened", "Кассета %@ открыта", "Kassette %@ geöffnet"),
"Cassette : %@ → %@": ("Cassette: %@ → %@", "Кассета: %@ → %@", "Kassette: %@ → %@"),
"Cassette introuvable : %@": ("Cassette not found: %@", "Кассета не найдена: %@", "Kassette nicht gefunden: %@"),
"Changements de l'IA annulés": ("AI changes undone", "Изменения ИИ отменены", "KI-Änderungen rückgängig gemacht"),
"Clique un élément dans l'aperçu (titre, logo, code, tracklist…) pour le déplacer, l'agrandir ou le masquer.": ("Click an element in the preview (title, logo, code, tracklist…) to move, resize or hide it.", "Нажми на элемент в превью (название, логотип, код, треклист…), чтобы переместить, увеличить или скрыть его.", "Klick ein Element in der Vorschau an (Titel, Logo, Code, Trackliste…), um es zu verschieben, zu vergrößern oder auszublenden."),
"Code Spotify trop petit (%@ mm) : 20 mm de large minimum.": ("Spotify code too small (%@ mm): at least 20 mm wide.", "Код Spotify слишком мал (%@ мм): минимум 20 мм в ширину.", "Spotify-Code zu klein (%@ mm): mindestens 20 mm breit."),
"Code-barres trop bas (%@ mm) : 6 mm minimum pour être scanné.": ("Barcode too short (%@ mm): at least 6 mm to scan.", "Штрихкод слишком низкий (%@ мм): минимум 6 мм для сканирования.", "Barcode zu niedrig (%@ mm): mindestens 6 mm zum Scannen."),
"Composer : %@": ("Compose: %@", "Подобрать: %@", "Zusammenstellen: %@"),
"Copie %@ créée et ouverte": ("Copy %@ created and opened", "Копия %@ создана и открыта", "Kopie %@ erstellt und geöffnet"),
"Couleur": ("Colour", "Цвет", "Farbe"),
"Couleur du design": ("Design colour", "Цвет дизайна", "Designfarbe"),
"Côté du QR": ("QR size", "Сторона QR", "QR-Größe"),
"Désélectionner": ("Deselect", "Снять выделение", "Auswahl aufheben"),
"Effacer l'historique": ("Clear history", "Очистить историю", "Verlauf löschen"),
"Effacer le fil": ("Clear thread", "Очистить переписку", "Verlauf leeren"),
"En plus de la jaquette, l'IA peut changer la Mixtape (ordre, faces, morceaux, C60/C90, bande, Dolby, coque, titre), les réglages de la cassette et la Collection (créer, dupliquer, renommer). Tout s'annule en un clic. Elle demande toujours avant de supprimer une cassette, ne touche jamais aux clés, aux comptes ni aux fichiers audio, et ne lance ni l'enregistrement ni l'impression.": ("Besides the J-card, the AI can change the Mixtape (order, sides, tracks, C60/C90, tape, Dolby, shell, title), the cassette settings and the Collection (create, duplicate, rename). Everything can be undone in one click. It always asks before deleting a cassette, never touches keys, accounts or audio files, and never starts recording or printing.", "Кроме вкладыша, ИИ может менять Микстейп (порядок, стороны, треки, C60/C90, ленту, Dolby, корпус, название), настройки кассеты и Коллекцию (создать, дублировать, переименовать). Всё отменяется одним щелчком. Перед удалением кассеты он всегда спрашивает, никогда не трогает ключи, аккаунты и аудиофайлы и не запускает запись или печать.", "Neben dem J-Card kann die KI das Mixtape (Reihenfolge, Seiten, Titel, C60/C90, Band, Dolby, Gehäuse, Name), die Kassetteneinstellungen und die Sammlung (anlegen, duplizieren, umbenennen) ändern. Alles lässt sich mit einem Klick rückgängig machen. Vor dem Löschen einer Kassette fragt sie immer nach, sie rührt nie Schlüssel, Konten oder Audiodateien an und startet weder Aufnahme noch Druck."),
"Face A : %lld morceaux · face B : %lld morceaux": ("Side A: %lld tracks · side B: %lld tracks", "Сторона A: треков %lld · сторона B: треков %lld", "Seite A: %lld Titel · Seite B: %lld Titel"),
"Fichier introuvable dans le dossier audio : %@": ("File not found in the audio folder: %@", "Файл не найден в аудиопапке: %@", "Datei im Audioordner nicht gefunden: %@"),
"Glisse l'image dans l'aperçu pour choisir la partie visible.": ("Drag the image in the preview to choose the visible part.", "Перетащи изображение в превью, чтобы выбрать видимую часть.", "Zieh das Bild in der Vorschau, um den sichtbaren Ausschnitt zu wählen."),
"Historique IA (%lld)": ("AI history (%lld)", "История ИИ (%lld)", "KI-Verlauf (%lld)"),
"IA expert": ("Expert AI", "ИИ-эксперт", "KI-Experte"),
"Il n'y a rien à annuler.": ("There's nothing to undo.", "Отменять нечего.", "Es gibt nichts rückgängig zu machen."),
"Image « %@ » (%@)": ("Image “%@” (%@)", "Изображение «%@» (%@)", "Bild „%@“ (%@)"),
"Impossible : %@": ("Not possible: %@", "Невозможно: %@", "Nicht möglich: %@"),
"Jaquette remise comme après « %@ »": ("J-card restored to how it was after “%@”", "Вкладыш возвращён к состоянию после «%@»", "J-Card wie nach „%@“ wiederhergestellt"),
"Je pars des vraies éditions cassette si j'en trouve, sinon de ta pochette. Clique sur « Proposer » pour 3 variantes ; pour une retouche précise, écris-la dans « Modifier avec l'IA ».": ("I start from real cassette editions if I find any, otherwise from your cover. Click “Propose” for 3 variants; for a precise tweak, write it in “Edit with AI”.", "Я начинаю с настоящих кассетных изданий, если найду, иначе с твоей обложки. Нажми «Предложить» для 3 вариантов; для точной правки напиши её в «Изменить с ИИ».", "Ich gehe von echten Kassettenausgaben aus, wenn ich welche finde, sonst von deinem Cover. Klick auf „Vorschlagen“ für 3 Varianten; für eine genaue Änderung schreib sie in „Mit KI ändern“."),
"L'IA demande de supprimer cette cassette de la Collection. Tes fichiers audio ne sont pas touchés.": ("The AI asks to delete this cassette from the Collection. Your audio files are not touched.", "ИИ просит удалить эту кассету из Коллекции. Твои аудиофайлы не затрагиваются.", "Die KI möchte diese Kassette aus der Sammlung löschen. Deine Audiodateien bleiben unberührt."),
"L'IA ne touche pas à « %@ » (clés, comptes, fichiers et sorties restent à toi).": ("The AI doesn't touch “%@” (keys, accounts, files and outputs stay yours).", "ИИ не трогает «%@» (ключи, аккаунты, файлы и выходы — твои).", "Die KI rührt „%@“ nicht an (Schlüssel, Konten, Dateien und Ausgänge bleiben deine Sache)."),
"LaFleurStudio · %@ · %@": ("LaFleurStudio · %@ · %@", "LaFleurStudio · %@ · %@", "LaFleurStudio · %@ · %@"),
"Largeur du code Spotify": ("Spotify code width", "Ширина кода Spotify", "Breite des Spotify-Codes"),
"Les réglages de la cassette demandent le mode expert (Réglages → IA).": ("Cassette settings need expert mode (Settings → AI).", "Для настроек кассеты нужен режим эксперта (Настройки → ИИ).", "Kassetteneinstellungen brauchen den Expertenmodus (Einstellungen → KI)."),
"Longueur de cassette incomprise : %@": ("Cassette length not understood: %@", "Длина кассеты не понята: %@", "Kassettenlänge nicht verstanden: %@"),
"Masquer": ("Hide", "Скрыть", "Ausblenden"),
"Mode expert": ("Expert mode", "Режим эксперта", "Expertenmodus"),
"Mode expert : l'IA a tous les droits": ("Expert mode: the AI has full rights", "Режим эксперта: у ИИ все права", "Expertenmodus: Die KI hat alle Rechte"),
"Mode expert : l'IA peut aussi agir sur la Mixtape, les réglages de la cassette et la Collection (Réglages → IA).": ("Expert mode: the AI can also act on the Mixtape, cassette settings and Collection (Settings → AI).", "Режим эксперта: ИИ может также менять Микстейп, настройки кассеты и Коллекцию (Настройки → ИИ).", "Expertenmodus: Die KI kann auch Mixtape, Kassetteneinstellungen und Sammlung ändern (Einstellungen → KI)."),
"Modification annulée": ("Change undone", "Изменение отменено", "Änderung rückgängig gemacht"),
"Modifier avec l'IA · %@": ("Edit with AI · %@", "Изменить с ИИ · %@", "Mit KI ändern · %@"),
"Morceau introuvable : %@": ("Track not found: %@", "Трек не найден: %@", "Titel nicht gefunden: %@"),
"Nouvelle cassette %@": ("New cassette %@", "Новая кассета %@", "Neue Kassette %@"),
"Ou glisse l'image dans l'aperçu des étiquettes.": ("Or drag the image in the label preview.", "Или перетащи изображение в превью наклеек.", "Oder zieh das Bild in der Etikettenvorschau."),
"Ouvrir la cassette": ("Open the cassette", "Открыть кассету", "Kassette öffnen"),
"Pochette": ("Cover", "Обложка", "Cover"),
"Position": ("Position", "Положение", "Position"),
"QR code trop petit (%@ mm) : 10 mm minimum pour être scanné par un téléphone.": ("QR code too small (%@ mm): at least 10 mm for a phone to scan.", "QR-код слишком мал (%@ мм): минимум 10 мм для сканирования телефоном.", "QR-Code zu klein (%@ mm): mindestens 10 mm zum Scannen mit dem Handy."),
"Refaire cette demande": ("Redo this request", "Повторить запрос", "Anfrage wiederholen"),
"Revenir à cette version": ("Go back to this version", "Вернуться к этой версии", "Zu dieser Version zurück"),
"Rien n'a été changé.": ("Nothing was changed.", "Ничего не изменено.", "Nichts wurde geändert."),
"Réglage inconnu : %@": ("Unknown setting: %@", "Неизвестная настройка: %@", "Unbekannte Einstellung: %@"),
"Régénérer la variante %@": ("Regenerate variant %@", "Перегенерировать вариант %@", "Variante %@ neu erzeugen"),
"Sous 5 pt, l'app prévient : c'est trop petit pour être lu une fois imprimé.": ("Below 5 pt the app warns you: too small to read once printed.", "Меньше 5 pt приложение предупредит: после печати не прочесть.", "Unter 5 pt warnt die App: gedruckt zu klein zum Lesen."),
"Suppression de %@ à confirmer": ("Deletion of %@ to confirm", "Удаление %@ нужно подтвердить", "Löschen von %@ bestätigen"),
"Taille %@ pt": ("Size %@ pt", "Размер %@ pt", "Größe %@ pt"),
"Taille et place par défaut": ("Default size and position", "Размер и место по умолчанию", "Standardgröße und -position"),
"Taille par défaut": ("Default size", "Размер по умолчанию", "Standardgröße"),
"Tailles": ("Sizes", "Размеры", "Größen"),
"Titre : %@ → %@": ("Title: %@ → %@", "Название: %@ → %@", "Titel: %@ → %@"),
"Valeur refusée pour %@ : %@": ("Value rejected for %@: %@", "Значение отклонено для %@: %@", "Wert für %@ abgelehnt: %@"),
"Variante %@": ("Variant %@", "Вариант %@", "Variante %@"),
"Voile": ("Veil", "Вуаль", "Schleier"),
"Vérifier avec l'IA": ("Check with AI", "Проверить с ИИ", "Mit KI prüfen"),
"Zoom de l'image": ("Image zoom", "Масштаб изображения", "Bildzoom"),
"x %@ mm": ("x %@ mm", "x %@ мм", "x %@ mm"),
"y %@ mm": ("y %@ mm", "y %@ мм", "y %@ mm"),
"« %@ » ajouté en face %@": ("“%@” added to side %@", "«%@» добавлен на сторону %@", "„%@“ zu Seite %@ hinzugefügt"),
"« %@ » demande le mode expert (Réglages → IA).": ("“%@” needs expert mode (Settings → AI).", "Для «%@» нужен режим эксперта (Настройки → ИИ).", "„%@“ braucht den Expertenmodus (Einstellungen → KI)."),
"« %@ » retiré": ("“%@” removed", "«%@» убран", "„%@“ entfernt"),
"« %@ » → face %@, position %lld": ("“%@” → side %@, position %lld", "«%@» → сторона %@, позиция %lld", "„%@“ → Seite %@, Position %lld"),
"Échelle": ("Scale", "Масштаб", "Maßstab"),
"Élément": ("Element", "Элемент", "Element"),
"Équilibrer les faces": ("Balance the sides", "Распределить стороны", "Seiten ausgleichen"),
"Étiquette avec la pochette en fond : voile faible, les textes risquent d'être difficiles à lire sur l'image.": ("Label with cover background: weak veil, text may be hard to read over the image.", "Наклейка с обложкой на фоне: слабая вуаль, текст может плохо читаться на изображении.", "Etikett mit Cover im Hintergrund: schwacher Schleier, Text ist auf dem Bild vielleicht schwer lesbar."),
"↶ Annuler": ("↶ Undo", "↶ Отменить", "↶ Rückgängig"),
"Position horizontale": ("Horizontal position", "По горизонтали", "Horizontale Position"),
"Position verticale": ("Vertical position", "По вертикали", "Vertikale Position"),
"Petite pochette": ("Small cover", "Маленькая обложка", "Kleines Cover"),
"Pochette en fond": ("Cover as background", "Обложка на фоне", "Cover als Hintergrund"),
"Sans pochette": ("No cover", "Без обложки", "Ohne Cover"),
"Étiquettes de K7": ("Cassette labels", "Наклейки кассеты", "Kassettenetiketten"),
"Ex. « titre plus gros », « retire la pochette de l'étiquette », « code-barres de 30 mm », « décale l'image vers la gauche »": ("E.g. “bigger title”, “remove the cover from the label”, “30 mm barcode”, “move the image to the left”", "Напр. «название крупнее», «убери обложку с наклейки», «штрихкод 30 мм», «сдвинь изображение влево»", "Z. B. „Titel größer“, „Cover vom Etikett entfernen“, „Barcode 30 mm“, „Bild nach links schieben“"),
"Ex. « mets Glass en face B », « passe en C90 », « bande Type I sans Dolby »": ("E.g. “put Glass on side B”, “switch to C90”, “Type I tape without Dolby”", "Напр. «поставь Glass на сторону B», «сделай C90», «лента Type I без Dolby»", "Z. B. „Glass auf Seite B“, „auf C90 umstellen“, „Typ-I-Band ohne Dolby“"),
"Image du recto": ("Front image", "Изображение лицевой стороны", "Frontbild"),
"Titre": ("Title", "Название", "Titel"),
"Artiste": ("Artist", "Исполнитель", "Künstler"),
"Logo de la maison de disque (recto)": ("Label logo (front)", "Логотип лейбла (лицевая сторона)", "Labellogo (Vorderseite)"),
"Texte de tranche": ("Spine text", "Текст корешка", "Rückentext"),
"Logo de la maison de disque (tranche)": ("Label logo (spine)", "Логотип лейбла (корешок)", "Labellogo (Rücken)"),
"Numéro de catalogue (tranche)": ("Catalogue number (spine)", "Каталожный номер (корешок)", "Katalognummer (Rücken)"),
"Mentions techniques (bande, Dolby)": ("Technical info (tape, Dolby)", "Технические данные (лента, Dolby)", "Technische Angaben (Band, Dolby)"),
"Codes (code-barres, QR, Spotify)": ("Codes (barcode, QR, Spotify)", "Коды (штрихкод, QR, Spotify)", "Codes (Barcode, QR, Spotify)"),
"Ligne ℗ ©": ("℗ © line", "Строка ℗ ©", "℗-©-Zeile"),
"Tracklist": ("Tracklist", "Треклист", "Trackliste"),
"Notes": ("Notes", "Заметки", "Notizen"),
"Crédits": ("Credits", "Титры", "Credits"),
"Titre (étiquette)": ("Title (label)", "Название (наклейка)", "Titel (Etikett)"),
"Lettre de face (étiquette)": ("Side letter (label)", "Буква стороны (наклейка)", "Seitenbuchstabe (Etikett)"),
"Pochette (étiquette)": ("Cover (label)", "Обложка (наклейка)", "Cover (Etikett)"),
"C60 / NR (étiquette)": ("C60 / NR (label)", "C60 / NR (наклейка)", "C60 / NR (Etikett)"),
"Ligne du bas (étiquette)": ("Bottom line (label)", "Нижняя строка (наклейка)", "Untere Zeile (Etikett)"),
"Texte de l'obi": ("Obi text", "Текст оби", "Obi-Text"),
"Recto": ("Front", "Лицевая сторона", "Vorderseite"),
"Tranche": ("Spine", "Корешок", "Rücken"),
"Rabat": ("Flap", "Клапан", "Lasche"),
"Volets": ("Panels", "Панели", "Felder"),
"Étiquettes": ("Labels", "Наклейки", "Etiketten"),
"Obi": ("Obi", "Оби", "Obi"),
"Rotation": ("Rotation", "Поворот", "Drehung"),
"Opacité": ("Opacity", "Непрозрачность", "Deckkraft"),
"Taille": ("Size", "Размер", "Größe"),
}
