T = {
"C'est celui-là": ("That's the one", "Вот этот", "Das ist er"),
"C60 · 30 min/face": ("C60 · 30 min/side", "C60 · 30 мин/сторона", "C60 · 30 Min./Seite"),
"C90 · 45 min/face": ("C90 · 45 min/side", "C90 · 45 мин/сторона", "C90 · 45 Min./Seite"),
"Cassette": ("Tape", "Кассета", "Kassette"),
"Cassette depuis le dossier (sans Spotify)": ("Tape from folder (no Spotify)", "Кассета из папки (без Spotify)", "Kassette aus Ordner (ohne Spotify)"),
"Cassette face %@": ("Tape side %@", "Кассета, сторона %@", "Kassette Seite %@"),
"Ce fichier est-il bien « %@ » de %@ (%@) ?": ("Is this file really “%@” by %@ (%@)?", "Это действительно «%@» — %@ (%@)?", "Ist diese Datei wirklich „%@“ von %@ (%@)?"),
"Ce que ça coûte, ce qui est envoyé": ("What it costs, what is sent", "Сколько стоит и что отправляется", "Was es kostet, was gesendet wird"),
"Cette imprimante n'est pas encore calibrée : elle imprime sans correction.": ("This printer isn't calibrated yet: it prints without correction.", "Этот принтер ещё не откалиброван: печать без коррекции.", "Dieser Drucker ist noch nicht kalibriert: er druckt ohne Korrektur."),
"Chercher les infos de l'album sur le web": ("Look up album info on the web", "Найти данные альбома в интернете", "Albuminfos im Web suchen"),
"Chercher sur MusicBrainz": ("Search MusicBrainz", "Искать на MusicBrainz", "Auf MusicBrainz suchen"),
"Chercher sur MusicBrainz et Discogs": ("Search MusicBrainz and Discogs", "Искать на MusicBrainz и Discogs", "Auf MusicBrainz und Discogs suchen"),
"Chercher un album ou coller un lien…": ("Search an album or paste a link…", "Найди альбом или вставь ссылку…", "Album suchen oder Link einfügen…"),
"Chercher une cassette, un artiste…": ("Search a tape, an artist…", "Искать кассету, исполнителя…", "Kassette, Künstler suchen…"),
"Chiffres sous les barres": ("Digits under the bars", "Цифры под штрихами", "Ziffern unter den Strichen"),
"Choisir un fichier…": ("Choose a file…", "Выбрать файл…", "Datei wählen…"),
"Choisir une image…": ("Choose an image…", "Выбрать изображение…", "Bild wählen…"),
"Choisir…": ("Choose…", "Выбрать…", "Wählen…"),
"Claude : pas de clé": ("Claude: no key", "Claude: нет ключа", "Claude: kein Schlüssel"),
"Claude : prêt": ("Claude: ready", "Claude: готов", "Claude: bereit"),
"Claude est l'assistant intégré à l'app. Il t'aide à préparer la cassette, mais c'est toi qui décides : tu acceptes, modifies ou refuses chacune de ses propositions.": ("Claude is the app's built-in assistant. It helps you prepare the tape, but you decide: you accept, edit or reject each suggestion.", "Claude — встроенный помощник. Он помогает готовить кассету, но решаешь ты: принимаешь, меняешь или отклоняешь каждое предложение.", "Claude ist der eingebaute Assistent. Er hilft dir bei der Kassette, aber du entscheidest: Du übernimmst, änderst oder verwirfst jeden Vorschlag."),
"Claude part de leurs scans pour la première proposition.": ("Claude starts from their scans for the first proposal.", "Claude берёт их сканы за основу первого предложения.", "Claude nutzt ihre Scans für den ersten Vorschlag."),
"Claude peut chercher sur des sites choisis (sources citées)": ("Claude may search chosen sites (sources cited)", "Claude может искать на выбранных сайтах (с источниками)", "Claude darf auf ausgewählten Seiten suchen (mit Quellen)"),
"Claude répond dans cette langue. L'interface change au prochain lancement de l'app.": ("Claude answers in this language. The interface changes the next time the app starts.", "Claude отвечает на этом языке. Интерфейс сменится при следующем запуске.", "Claude antwortet in dieser Sprache. Die Oberfläche wechselt beim nächsten Start."),
"Clé API": ("API key", "Ключ API", "API-Schlüssel"),
"Clé de contrôle calculée : %@": ("Check digit computed: %@", "Контрольная цифра: %@", "Prüfziffer berechnet: %@"),
"Coche ce que tu gardes. Rien n'est ajouté sans toi.": ("Tick what you keep. Nothing is added without you.", "Отметь, что оставить. Без тебя ничего не добавится.", "Hake an, was du behältst. Nichts wird ohne dich hinzugefügt."),
"Code-barres %@ %@": ("Barcode %@ %@", "Штрихкод %@ %@", "Strichcode %@ %@"),
"Codes": ("Codes", "Коды", "Codes"),
"Codes scannables": ("Codes scannable", "Коды читаются", "Codes scannbar"),
"✓ Codes scannables": ("✓ Codes scannable", "✓ Коды читаются", "✓ Codes scannbar"),
"Commencer": ("Start", "Начать", "Loslegen"),
"Composer avec Claude (mixtape)": ("Compose with Claude (mixtape)", "Собрать с Claude (микстейп)", "Mit Claude zusammenstellen (Mixtape)"),
"Composer la sélection": ("Compose the selection", "Собрать подборку", "Auswahl zusammenstellen"),
"Compte Spotify": ("Spotify account", "Аккаунт Spotify", "Spotify-Konto"),
"Compte à rebours : %lld s": ("Countdown: %lld s", "Обратный отсчёт: %lld с", "Countdown: %lld s"),
"Conditions d'utilisation": ("Terms of use", "Условия использования", "Nutzungsbedingungen"),
"Connecté ✓": ("Connected ✓", "Подключено ✓", "Verbunden ✓"),
"Continuer": ("Continue", "Продолжить", "Weiter"),
"Couleurs": ("Colours", "Цвета", "Farben"),
"Couleurs et polices": ("Colours and fonts", "Цвета и шрифты", "Farben und Schriften"),
"Coupe, pliage, fond perdu": ("Crop, fold, bleed", "Обрез, сгиб, вылеты", "Schnitt, Falz, Beschnitt"),
"Couper la tonalité": ("Stop the tone", "Выключить тон", "Ton stoppen"),
"Crédits": ("Credits", "Титры", "Credits"),
"Custom": ("Custom", "Своя", "Eigene"),
"Descendre": ("Move down", "Вниз", "Nach unten"),
"Direction artistique · Claude": ("Art direction · Claude", "Арт-дирекция · Claude", "Art Direction · Claude"),
"Discogs (jeton personnel gratuit)": ("Discogs (free personal token)", "Discogs (бесплатный личный токен)", "Discogs (kostenloses persönliches Token)"),
"Discogs ajoute les photos de milliers d'éditions K7 : Claude s'en sert pour sa première proposition.": ("Discogs adds photos of thousands of cassette editions: Claude uses them for its first proposal.", "Discogs добавляет фото тысяч кассетных изданий: Claude использует их для первого предложения.", "Discogs liefert Fotos von tausenden Kassettenausgaben: Claude nutzt sie für den ersten Vorschlag."),
"Dos": ("Back", "Клапан", "Rücken"),
"Dossier audio": ("Audio folder", "Папка с аудио", "Audio-Ordner"),
"Dupliquer": ("Duplicate", "Дублировать", "Duplizieren"),
"Durée réelle d'une face : %@": ("Real side length: %@", "Реальная длина стороны: %@", "Tatsächliche Seitenlänge: %@"),
"Déconnecter": ("Disconnect", "Отключить", "Trennen"),
"Décalage : %@ mm horizontal, %@ mm vertical.": ("Offset: %@ mm horizontal, %@ mm vertical.", "Смещение: %@ мм по горизонтали, %@ мм по вертикали.", "Versatz: %@ mm horizontal, %@ mm vertikal."),
"Demande à Claude… (« plus sombre », « plus 90s »)": ("Ask Claude… (“darker”, “more 90s”)", "Попроси Claude… («темнее», «больше 90-х»)", "Frag Claude… („dunkler“, „mehr 90er“)"),
"Dépasse la bande : retire ou déplace un morceau.": ("Over the tape length: remove or move a track.", "Не помещается на ленту: убери или перенеси трек.", "Zu lang für das Band: entferne oder verschiebe einen Titel."),
"Déroulé": ("Run order", "Порядок", "Ablauf"),
"En cours": ("Playing", "Идёт", "Läuft"),
"En option, les mêmes règles à la verticale (si ton imprimante n'a pas la même erreur dans les deux sens) :": ("Optional: the same rulers vertically (if your printer errs differently in each direction):", "По желанию: те же линейки вертикально (если принтер ошибается по-разному в двух направлениях):", "Optional: dieselben Lineale senkrecht (falls dein Drucker in beiden Richtungen unterschiedlich abweicht):"),
"Enregistrée": ("Recorded", "Записана", "Aufgenommen"),
"Envoyer": ("Send", "Отправить", "Senden"),
"Exporter": ("Export", "Экспорт", "Exportieren"),
"Exporter quand même": ("Export anyway", "Всё равно экспортировать", "Trotzdem exportieren"),
"FACE %@ · %@": ("SIDE %@ · %@", "СТОРОНА %@ · %@", "SEITE %@ · %@"),
"Face": ("Side", "Сторона", "Seite"),
"Face %@": ("Side %@", "Сторона %@", "Seite %@"),
"Face A": ("Side A", "Сторона A", "Seite A"),
"Face A terminée. Arrête la platine, retourne la cassette, puis remets-la en ENREGISTREMENT + PAUSE.": ("Side A done. Stop the deck, flip the tape, then set it back to RECORD + PAUSE.", "Сторона A готова. Останови деку, переверни кассету и снова включи ЗАПИСЬ + ПАУЗА.", "Seite A fertig. Deck stoppen, Kassette umdrehen, dann wieder AUFNAHME + PAUSE."),
"Face B": ("Side B", "Сторона B", "Seite B"),
"Face B terminée. C'est dans la boîte ✿ Arrête la platine.": ("Side B done. It's in the can ✿ Stop the deck.", "Сторона B готова. Готово ✿ Останови деку.", "Seite B fertig. Im Kasten ✿ Deck stoppen."),
"Fait": ("Done", "Готово", "Fertig"),
"Fermer": ("Close", "Закрыть", "Schließen"),
"Fond": ("Background", "Фон", "Hintergrund"),
"Format": ("Format", "Формат", "Format"),
"Garder l'ordre (auto)": ("Keep the order (auto)", "Сохранить порядок (авто)", "Reihenfolge behalten (auto)"),
"Glisse ou clic droit pour réordonner · ⇄ change de face · × retire": ("Drag or right-click to reorder · ⇄ switches side · × removes", "Перетащи или правый клик для порядка · ⇄ сменить сторону · × убрать", "Ziehen oder Rechtsklick zum Ordnen · ⇄ Seite wechseln · × entfernen"),
"Glisse pour tourner la cassette": ("Drag to turn the tape", "Тяни, чтобы повернуть кассету", "Ziehen, um die Kassette zu drehen"),
"Gratuit, sans compte : albums, tracklists, maisons de disque, scans des vraies éditions cassette.": ("Free, no account: albums, tracklists, labels, scans of real cassette editions.", "Бесплатно, без аккаунта: альбомы, треклисты, лейблы, сканы настоящих кассетных изданий.", "Kostenlos, ohne Konto: Alben, Tracklists, Labels, Scans echter Kassettenausgaben."),
"Guide pas à pas…": ("Step-by-step guide…", "Пошаговая инструкция…", "Schritt-für-Schritt-Anleitung…"),
"Ignorer": ("Ignore", "Пропустить", "Ignorieren"),
"Importer une police…": ("Import a font…", "Импорт шрифта…", "Schrift importieren…"),
"Imprimante": ("Printer", "Принтер", "Drucker"),
"Imprimante et papier": ("Printer and paper", "Принтер и бумага", "Drucker und Papier"),
"Imprime à 100 %, pas « Ajuster à la page ».": ("Print at 100 %, not “Fit to page”.", "Печатай в 100 %, не «По размеру страницы».", "Mit 100 % drucken, nicht „An Seite anpassen“."),
"Imprimer la règle": ("Print the ruler", "Напечатать линейку", "Lineal drucken"),
"Imprimer la règle d'abord": ("Print the ruler first", "Сначала напечатать линейку", "Zuerst das Lineal drucken"),
"Imprimer quand même": ("Print anyway", "Всё равно печатать", "Trotzdem drucken"),
"Imprimer quand même avec ce défaut": ("Print anyway with this issue", "Печатать с этим недочётом", "Trotz dieses Fehlers drucken"),
"Imprimer à 100 % (jamais « ajuster à la page ») · traits pleins : coupe · pointillés : pliage · usage personnel, non commercial": ("Print at 100 % (never “fit to page”) · solid lines: cut · dotted: fold · personal, non-commercial use", "Печатать в 100 % (никогда «по размеру страницы») · сплошные: резать · пунктир: сгибать · только личное некоммерческое использование", "Mit 100 % drucken (nie „an Seite anpassen“) · durchgezogen: schneiden · gepunktet: falzen · privat, nicht kommerziell"),
"Imprimer à la bonne taille": ("Print at the right size", "Печать в правильном размере", "In der richtigen Größe drucken"),
"Imprimer…": ("Print…", "Печать…", "Drucken…"),
"Ignorer ": ("Ignore ", "Пропустить ", "Ignorieren "),
}
