T = {
"J'ai lu et j'accepte ces conditions": ("I have read and accept these terms", "Я прочитал(а) и принимаю эти условия", "Ich habe diese Bedingungen gelesen und akzeptiere sie"),
"J-card": ("J-card", "J-card", "J-Card"),
"J-card, O-card, obi : papier mat ou satiné de 170 à 250 g/m², A4.": ("J-card, O-card, obi: matte or satin paper, 170–250 g/m², A4.", "J-card, O-card, оби: матовая или сатиновая бумага 170–250 г/м², A4.", "J-Card, O-Card, Obi: mattes oder seidenmattes Papier, 170–250 g/m², A4."),
"Je pars des vraies éditions cassette si j'en trouve, sinon de ta pochette. Dis-moi l'ambiance, ou clique sur « Proposer ».": ("I start from real cassette editions if I find any, otherwise from your cover. Tell me the mood, or click “Propose”.", "Я начну с настоящих кассетных изданий, если найду, иначе — с твоей обложки. Опиши настроение или нажми «Предложить».", "Ich starte mit echten Kassettenausgaben, falls ich welche finde, sonst mit deinem Cover. Sag mir die Stimmung oder klick „Vorschlagen“."),
"L'app joue seulement sur cette sortie ; le reste du Mac ne change pas.": ("The app plays only on this output; the rest of the Mac is unchanged.", "Приложение играет только на этот выход; остальной Mac не меняется.", "Die App spielt nur über diesen Ausgang; der Rest des Mac bleibt unverändert."),
"La cassette est retirée de la collection. Tes fichiers audio ne sont pas touchés.": ("The tape is removed from the collection. Your audio files are not touched.", "Кассета удаляется из коллекции. Твои аудиофайлы не трогаются.", "Die Kassette wird aus der Sammlung entfernt. Deine Audiodateien bleiben unberührt."),
"La platine repart : clique ici": ("The deck restarts: click here", "Дека поехала: нажми здесь", "Das Deck läuft wieder: hier klicken"),
"LaFleurStudio → Réglages → Impression. C'est tout : l'app corrige toutes tes impressions.": ("LaFleurStudio → Settings → Printing. That's it: the app corrects all your prints.", "LaFleurStudio → Настройки → Печать. Всё: приложение исправит всю печать.", "LaFleurStudio → Einstellungen → Drucken. Das war's: die App korrigiert alle Drucke."),
"LaFleurStudio · règle de calibrage (%@)": ("LaFleurStudio · calibration ruler (%@)", "LaFleurStudio · калибровочная линейка (%@)", "LaFleurStudio · Kalibrierlineal (%@)"),
"Langue de l'app et de Claude": ("App and Claude language", "Язык приложения и Claude", "Sprache der App und von Claude"),
"Le PDF exporté garde le fond perdu (3 mm) pour une impression en boutique ; le calibrage ne s'applique qu'à ton imprimante.": ("The exported PDF keeps the 3 mm bleed for a print shop; calibration only applies to your printer.", "Экспортированный PDF сохраняет вылеты 3 мм для типографии; калибровка действует только на твой принтер.", "Das exportierte PDF behält 3 mm Beschnitt für die Druckerei; die Kalibrierung gilt nur für deinen Drucker."),
"Le morceau n'est pas dans ton dossier audio. Sans fichier, il ne peut pas être enregistré.": ("The track isn't in your audio folder. Without a file it can't be recorded.", "Трека нет в папке с аудио. Без файла его нельзя записать.", "Der Titel ist nicht in deinem Audio-Ordner. Ohne Datei kann er nicht aufgenommen werden."),
"Lecture": ("Playback", "Воспроизведение", "Wiedergabe"),
"Logo de la maison de disque": ("Record label logo", "Логотип лейбла", "Label-Logo"),
"Maison de disque": ("Record label", "Лейбл", "Label"),
"Marque / modèle": ("Brand / model", "Марка / модель", "Marke / Modell"),
"Mes playlists…": ("My playlists…", "Мои плейлисты…", "Meine Playlists…"),
"Mesure la règle de 10 cm (ou celle de 4 pouces) avec une vraie règle, puis tape la valeur dans": ("Measure the 10 cm ruler (or the 4-inch one) with a real ruler, then type the value in", "Измерь линейку 10 см (или 4 дюйма) настоящей линейкой и введи значение в", "Miss das 10-cm-Lineal (oder das 4-Zoll-Lineal) mit einem echten Lineal und gib den Wert ein in"),
"Mesurer… (clique au bout de la bande)": ("Measure… (click at the end of the tape)", "Измерить… (нажми в конце ленты)", "Messen… (am Bandende klicken)"),
"Mise en page": ("Layout", "Макет", "Layout"),
"Mixtape": ("Mixtape", "Микстейп", "Mixtape"),
"Mode Concentration activé": ("Focus mode on", "Режим «Фокусирование» включён", "Fokus-Modus an"),
"Monter": ("Move up", "Вверх", "Nach oben"),
"MusicBrainz (gratuit, sans compte)": ("MusicBrainz (free, no account)", "MusicBrainz (бесплатно, без аккаунта)", "MusicBrainz (kostenlos, ohne Konto)"),
"MusicBrainz et Cover Art Archive": ("MusicBrainz and Cover Art Archive", "MusicBrainz и Cover Art Archive", "MusicBrainz und Cover Art Archive"),
"Ne colle jamais ta clé ailleurs (conversation, message, site) : n'importe qui pourrait l'utiliser à tes frais. Si ça arrive, supprime-la dans API keys et crée-en une nouvelle.": ("Never paste your key anywhere else (chat, message, website): anyone could use it at your expense. If it happens, delete it in API keys and create a new one.", "Никогда не вставляй ключ в другие места (чат, сообщение, сайт): им смогут пользоваться за твой счёт. Если так случилось, удали его в API keys и создай новый.", "Füge deinen Schlüssel nie woanders ein (Chat, Nachricht, Website): jeder könnte ihn auf deine Kosten nutzen. Falls doch, lösche ihn unter API keys und erstelle einen neuen."),
"Niveau réglé avec la tonalité": ("Level set with the tone", "Уровень выставлен по тону", "Pegel mit dem Ton eingestellt"),
"Notes (volet intérieur)": ("Notes (inner panel)", "Заметки (внутренняя панель)", "Notizen (Innenfeld)"),
"Nouvelle cassette": ("New tape", "Новая кассета", "Neue Kassette"),
"Nouvelle cassette…": ("New tape…", "Новая кассета…", "Neue Kassette…"),
"Numéro": ("Number", "Номер", "Nummer"),
"O-card cassingle": ("Cassingle O-card", "O-card (кассингл)", "Cassingle-O-Card"),
"Obi strip": ("Obi strip", "Оби", "Obi-Streifen"),
"Obtenir une clé API Claude, pas à pas": ("Getting a Claude API key, step by step", "Как получить ключ API Claude, шаг за шагом", "Einen Claude-API-Schlüssel bekommen, Schritt für Schritt"),
"Opacité": ("Opacity", "Непрозрачность", "Deckkraft"),
"Option : les traits rouges sont à 15 mm du bord gauche et du bord haut. S'ils sont décalés, note de combien.": ("Optional: the red lines are 15 mm from the left and top edges. If they're off, note by how much.", "По желанию: красные линии в 15 мм от левого и верхнего края. Если они смещены, запиши на сколько.", "Optional: Die roten Linien liegen 15 mm vom linken und oberen Rand. Sind sie verschoben, notiere um wie viel."),
"Options : règle verticale, décalage": ("Options: vertical ruler, offset", "Опции: вертикальная линейка, смещение", "Optionen: senkrechtes Lineal, Versatz"),
"Ouvrir": ("Open", "Открыть", "Öffnen"),
"Papier": ("Paper", "Бумага", "Papier"),
"Papier conseillé": ("Recommended paper", "Рекомендуемая бумага", "Empfohlenes Papier"),
"Passer au début de la face B": ("Skip to the start of side B", "Перейти к началу стороны B", "Zum Anfang von Seite B"),
"Passer à la fin de la face A": ("Skip to the end of side A", "Перейти к концу стороны A", "Zum Ende von Seite A"),
"Place": ("Position", "Место", "Position"),
"Place du QR": ("QR position", "Место QR", "QR-Position"),
"Platine sur %@": ("Deck set to %@", "Дека на %@", "Deck auf %@"),
"Plusieurs fichiers ressemblent à ce titre. Choisis le bon :": ("Several files look like this track. Pick the right one:", "Несколько файлов похожи на этот трек. Выбери нужный:", "Mehrere Dateien ähneln diesem Titel. Wähle die richtige:"),
"Pour ta mixtape je propose d'abord un collage des covers, puis ta propre image, le style K7 maison, ou un design dessiné. Dis-moi l'ambiance.": ("For your mixtape I first suggest a cover collage, then your own image, a homemade-tape style, or a drawn design. Tell me the mood.", "Для микстейпа я сначала предложу коллаж обложек, затем твою картинку, стиль самодельной кассеты или рисованный дизайн. Опиши настроение.", "Für dein Mixtape schlage ich zuerst eine Cover-Collage vor, dann dein eigenes Bild, den Selbstgemacht-Stil oder ein gezeichnetes Design. Sag mir die Stimmung."),
"Pourquoi Claude ?": ("Why Claude?", "Зачем Claude?", "Warum Claude?"),
"Proposer": ("Propose", "Предложить", "Vorschlagen"),
"Préparer la face B": ("Prepare side B", "Подготовить сторону B", "Seite B vorbereiten"),
"QR": ("QR", "QR", "QR"),
"QR code": ("QR code", "QR-код", "QR-Code"),
"Quatre réglages et une validation, et tu peux faire ta première cassette. Tout est modifiable plus tard dans Réglages.": ("Four settings and one confirmation, and you can make your first tape. Everything can be changed later in Settings.", "Четыре настройки и подтверждение — и можно делать первую кассету. Всё меняется потом в Настройках.", "Vier Einstellungen und eine Bestätigung, dann kannst du deine erste Kassette machen. Alles lässt sich später in den Einstellungen ändern."),
"Quitter": ("Quit", "Выйти", "Beenden"),
"Rangée dans le trousseau du Mac.": ("Stored in the Mac keychain.", "Хранится в связке ключей Mac.", "Im Schlüsselbund des Mac gespeichert."),
"Recherche web": ("Web search", "Поиск в интернете", "Websuche"),
"Recto": ("Front", "Лицевая сторона", "Vorderseite"),
"Relancer l'app maintenant": ("Restart the app now", "Перезапустить приложение", "App jetzt neu starten"),
"Relire": ("Rescan", "Перечитать", "Neu einlesen"),
"Relâche la pause de la platine… %lld": ("Release the deck's pause… %lld", "Отпусти паузу деки… %lld", "Pause am Deck lösen… %lld"),
"Remettre « %@ »": ("Put back “%@”", "Вернуть «%@»", "„%@“ zurücklegen"),
"Retirer ce morceau": ("Remove this track", "Убрать этот трек", "Diesen Titel entfernen"),
"Retirer de la cassette": ("Remove from tape", "Убрать с кассеты", "Von der Kassette entfernen"),
"Retirer de la cassette (ne sera pas enregistré)": ("Remove from tape (won't be recorded)", "Убрать с кассеты (не будет записан)", "Von der Kassette entfernen (wird nicht aufgenommen)"),
"Retirer l'image": ("Remove the image", "Убрать изображение", "Bild entfernen"),
"Règle de 10 cm": ("10 cm ruler", "Линейка 10 см", "10-cm-Lineal"),
"Règle de 4 pouces": ("4-inch ruler", "Линейка 4 дюйма", "4-Zoll-Lineal"),
"Règle verticale de %@ :": ("Vertical %@ ruler:", "Вертикальная линейка %@:", "Senkrechtes %@-Lineal:"),
"Réafficher les alertes ignorées (%lld)": ("Show ignored alerts again (%lld)", "Показать пропущенные предупреждения (%lld)", "Ignorierte Warnungen wieder zeigen (%lld)"),
"Réducteur de bruit": ("Noise reduction", "Шумоподавление", "Rauschunterdrückung"),
"Régénérer seulement la variante %@": ("Regenerate only variant %@", "Пересоздать только вариант %@", "Nur Variante %@ neu erzeugen"),
"Régénérer tout": ("Regenerate all", "Пересоздать все", "Alle neu erzeugen"),
"Réimprimer la jaquette": ("Reprint the J-card", "Перепечатать вкладыш", "J-Card neu drucken"),
"Réinitialiser (100 %)": ("Reset (100 %)", "Сбросить (100 %)", "Zurücksetzen (100 %)"),
"Se connecter…": ("Connect…", "Подключиться…", "Verbinden…"),
"Si Spotify refuse l'accès, c'est en général qu'il faut Premium, ou que la Redirect URI ne correspond pas exactement.": ("If Spotify refuses access, it usually means Premium is needed, or the Redirect URI doesn't match exactly.", "Если Spotify отказывает в доступе, обычно нужен Premium или Redirect URI не совпадает точно.", "Verweigert Spotify den Zugriff, fehlt meist Premium oder die Redirect URI stimmt nicht exakt."),
"Simple, sans auto-reverse : l'app dit de retourner la cassette": ("Simple, no auto-reverse: the app tells you to flip the tape", "Простая, без автореверса: приложение скажет перевернуть кассету", "Einfach, ohne Auto-Reverse: die App sagt dir, wann du umdrehen musst"),
"Son rôle": ("Its role", "Его роль", "Seine Rolle"),
"Sortie du Mac → LINE IN de la platine": ("Mac output → deck LINE IN", "Выход Mac → LINE IN деки", "Mac-Ausgang → LINE IN am Deck"),
"Sortie par défaut du Mac": ("Mac default output", "Выход Mac по умолчанию", "Standardausgang des Mac"),
"Sortie vers la platine": ("Output to the deck", "Выход на деку", "Ausgang zum Tapedeck"),
"Source : %@": ("Source: %@", "Источник: %@", "Quelle: %@"),
"Spotify : connecté": ("Spotify: connected", "Spotify: подключён", "Spotify: verbunden"),
"Spotify : non connecté": ("Spotify: not connected", "Spotify: не подключён", "Spotify: nicht verbunden"),
"Spotify n'ouvre son API qu'aux comptes Premium. Sans Premium, Spotify bloque l'appli : utilise alors « Cassette depuis le dossier » dans l'onglet Mixtape, qui marche sans Spotify.": ("Spotify only opens its API to Premium accounts. Without Premium, Spotify blocks the app: use “Tape from folder” in the Mixtape tab, which works without Spotify.", "Spotify открывает API только для Premium. Без Premium Spotify блокирует приложение: используй «Кассета из папки» во вкладке Микстейп — это работает без Spotify.", "Spotify öffnet seine API nur für Premium-Konten. Ohne Premium blockiert Spotify die App: nutze dann „Kassette aus Ordner“ im Tab Mixtape, das geht ohne Spotify."),
"Spotify n'ouvre son API qu'aux comptes Premium. Sans Premium, l'app marche quand même avec « Cassette depuis le dossier ».": ("Spotify only opens its API to Premium accounts. Without Premium, the app still works with “Tape from folder”.", "Spotify открывает API только для Premium. Без Premium приложение работает через «Кассета из папки».", "Spotify öffnet seine API nur für Premium-Konten. Ohne Premium funktioniert die App trotzdem mit „Kassette aus Ordner“."),
"Style": ("Style", "Стиль", "Stil"),
"Supprimer": ("Delete", "Удалить", "Löschen"),
"Supprimer %@ ?": ("Delete %@?", "Удалить %@?", "%@ löschen?"),
"Taille": ("Size", "Размер", "Größe"),
"Terminer": ("Finish", "Готово", "Fertig"),
"Tester": ("Test", "Проверить", "Testen"),
"Texte": ("Text", "Текст", "Text"),
"Texte au-dessus": ("Text above", "Текст сверху", "Text darüber"),
"Texte de l'obi": ("Obi text", "Текст оби", "Obi-Text"),
"Textes": ("Texts", "Тексты", "Texte"),
"Titre": ("Title", "Название", "Titel"),
"Titre en italique": ("Italic title", "Название курсивом", "Titel kursiv"),
"Titres, durées, maison de disque et pochette, sans Spotify.": ("Tracks, durations, label and cover, without Spotify.", "Треки, длительность, лейбл и обложка — без Spotify.", "Titel, Dauer, Label und Cover, ohne Spotify."),
"Tonalité 1 kHz": ("1 kHz tone", "Тон 1 кГц", "1-kHz-Ton"),
"Tout corriger": ("Fix everything", "Исправить всё", "Alles korrigieren"),
"Tout l'objet dans l'aperçu": ("The whole item in the preview", "Весь объект в окне", "Das ganze Objekt in der Vorschau"),
"Tranche": ("Spine", "Корешок", "Rücken"),
"Tu paies à l'usage : préparer une cassette coûte en général quelques centimes. La clé reste dans le trousseau de ton Mac. Claude reçoit les titres, les durées et les infos d'album, jamais tes fichiers audio.": ("You pay per use: preparing a tape usually costs a few cents. The key stays in your Mac's keychain. Claude receives titles, durations and album info, never your audio files.", "Оплата по факту: подготовка кассеты обычно стоит несколько центов. Ключ хранится в связке ключей Mac. Claude получает названия, длительности и данные альбома, но не аудиофайлы.", "Du zahlst nach Nutzung: eine Kassette vorzubereiten kostet meist ein paar Cent. Der Schlüssel bleibt im Schlüsselbund deines Mac. Claude bekommt Titel, Dauer und Albuminfos, nie deine Audiodateien."),
"Type": ("Type", "Тип", "Typ"),
"Type de platine": ("Deck type", "Тип деки", "Deck-Typ"),
"Versions (%lld)": ("Versions (%lld)", "Версии (%lld)", "Versionen (%lld)"),
"Vider les faces": ("Clear the sides", "Очистить стороны", "Seiten leeren"),
"Volets": ("Panels", "Панели", "Felder"),
"Vraies éditions cassette": ("Real cassette editions", "Настоящие кассетные издания", "Echte Kassettenausgaben"),
"Vérification avant impression": ("Pre-print check", "Проверка перед печатью", "Prüfung vor dem Druck"),
"Vérifier avec Claude": ("Check with Claude", "Проверить с Claude", "Mit Claude prüfen"),
"centimètres": ("centimetres", "сантиметрах", "Zentimetern"),
"pouces": ("inches", "дюймах", "Zoll"),
"pas de fichier": ("no file", "нет файла", "keine Datei"),
"⚠︎ fichier": ("⚠︎ file", "⚠︎ файл", "⚠︎ Datei"),
"« %@ » (%@) : aucun fichier trouvé": ("“%@” (%@): no file found", "«%@» (%@): файл не найден", "„%@“ (%@): keine Datei gefunden"),
"À remplir seulement si ton imprimante n'a pas la même erreur dans les deux sens.": ("Fill in only if your printer errs differently in each direction.", "Заполняй, только если принтер ошибается по-разному в двух направлениях.", "Nur ausfüllen, wenn dein Drucker in beiden Richtungen unterschiedlich abweicht."),
"À venir": ("Upcoming", "Далее", "Folgt"),
"Écouter": ("Listen", "Слушать", "Anhören"),
"Égaliser le volume entre les morceaux": ("Even out volume between tracks", "Выровнять громкость треков", "Lautstärke zwischen Titeln angleichen"),
"Équilibrer avec Claude": ("Balance with Claude", "Сбалансировать с Claude", "Mit Claude ausgleichen"),
"Étiquettes de K7": ("Cassette labels", "Этикетки кассеты", "Kassettenetiketten"),
"Étiquettes de K7 : papier autocollant A4 pleine page, mat. L'app imprime les traits de coupe.": ("Cassette labels: full-page A4 matte adhesive paper. The app prints the cut marks.", "Этикетки: самоклеящаяся матовая бумага A4 целым листом. Приложение печатает метки реза.", "Kassettenetiketten: mattes A4-Klebepapier, ganzseitig. Die App druckt die Schnittmarken."),
"• Design : propose couleurs, polices et variantes à partir de ta pochette.": ("• Design: suggests colours, fonts and variants from your cover.", "• Дизайн: предлагает цвета, шрифты и варианты по твоей обложке.", "• Design: schlägt Farben, Schriften und Varianten nach deinem Cover vor."),
"• Enregistrement : conseils selon ton type de bande et ta platine.": ("• Recording: tips for your tape type and deck.", "• Запись: советы под твой тип ленты и деку.", "• Aufnahme: Tipps für deinen Bandtyp und dein Deck."),
"• L'app est fournie telle quelle, sans garantie. L'auteur de LaFleurStudio n'est pas responsable de l'usage fait de l'app ni des objets produits.": ("• The app is provided as is, without warranty. The author of LaFleurStudio is not responsible for how the app is used or for the items produced.", "• Приложение предоставляется как есть, без гарантий. Автор LaFleurStudio не отвечает за использование приложения и созданные предметы.", "• Die App wird ohne Gewähr bereitgestellt. Der Autor von LaFleurStudio haftet nicht für die Nutzung der App oder die erzeugten Gegenstände."),
"• Les propositions de Claude peuvent contenir des erreurs : vérifie avant d'imprimer. Claude et Spotify ont leurs propres conditions d'utilisation.": ("• Claude's suggestions may contain errors: check before printing. Claude and Spotify have their own terms of use.", "• Предложения Claude могут содержать ошибки: проверяй перед печатью. У Claude и Spotify свои условия использования.", "• Claudes Vorschläge können Fehler enthalten: vor dem Drucken prüfen. Claude und Spotify haben eigene Nutzungsbedingungen."),
"• Mixtape : compose une sélection à partir d'une ambiance et équilibre les faces A/B selon la cassette.": ("• Mixtape: builds a selection from a mood and balances sides A/B for the tape.", "• Микстейп: собирает подборку по настроению и балансирует стороны A/B под кассету.", "• Mixtape: stellt eine Auswahl nach Stimmung zusammen und gleicht Seite A/B für die Kassette aus."),
"• Pochettes, logos, textes et infos venant de Spotify, MusicBrainz, Discogs ou d'ailleurs restent la propriété de leurs auteurs.": ("• Covers, logos, texts and info from Spotify, MusicBrainz, Discogs or elsewhere remain the property of their authors.", "• Обложки, логотипы, тексты и данные из Spotify, MusicBrainz, Discogs и других источников принадлежат их авторам.", "• Cover, Logos, Texte und Infos von Spotify, MusicBrainz, Discogs oder anderswo bleiben Eigentum ihrer Urheber."),
"• Textes : tranche, notes, crédits, numéro de catalogue.": ("• Texts: spine, notes, credits, catalogue number.", "• Тексты: корешок, заметки, титры, каталожный номер.", "• Texte: Rücken, Notizen, Credits, Katalognummer."),
"• Tu es seul responsable de ce que tu fais avec l'app et de ce que tu produis, y compris du respect des droits d'auteur et des marques.": ("• You alone are responsible for what you do with the app and what you produce, including respecting copyright and trademarks.", "• Ты один отвечаешь за то, что делаешь с приложением и что создаёшь, включая соблюдение авторских прав и товарных знаков.", "• Du allein bist verantwortlich für das, was du mit der App machst und herstellst, einschließlich Urheber- und Markenrechten."),
"• Usage personnel et non commercial uniquement : les cassettes, jaquettes et étiquettes créées ne sont pas faites pour être vendues, louées ou distribuées.": ("• Personal, non-commercial use only: the tapes, J-cards and labels created are not meant to be sold, rented or distributed.", "• Только личное некоммерческое использование: созданные кассеты, вкладыши и этикетки не предназначены для продажи, проката или распространения.", "• Nur private, nicht kommerzielle Nutzung: Die erstellten Kassetten, J-Cards und Etiketten sind nicht zum Verkauf, Verleih oder zur Verbreitung gedacht."),
"• Vérification : repère ce qui déborde, les codes pas scannables, le contraste trop faible.": ("• Check: spots overflowing text, unscannable codes, low contrast.", "• Проверка: находит вылезающий текст, нечитаемые коды, слабый контраст.", "• Prüfung: findet überlaufenden Text, nicht scannbare Codes, zu schwachen Kontrast."),
"⚠︎ Cette face dépasse la bande : la fin serait coupée.": ("⚠︎ This side is longer than the tape: the end would be cut.", "⚠︎ Эта сторона длиннее ленты: конец обрежется.", "⚠︎ Diese Seite ist länger als das Band: das Ende würde abgeschnitten."),
"⚠︎ Des morceaux n'ont pas de fichier audio : associe-les dans l'écran Mixtape.": ("⚠︎ Some tracks have no audio file: link them in the Mixtape screen.", "⚠︎ У некоторых треков нет аудиофайла: привяжи их на экране Микстейп.", "⚠︎ Einige Titel haben keine Audiodatei: ordne sie im Mixtape-Bildschirm zu."),
"✓ %@ : échelle %@ %%. Appliquée à toutes les impressions sur cette imprimante.": ("✓ %@: scale %@ %%. Applied to all prints on this printer.", "✓ %@: масштаб %@ %%. Применяется ко всей печати на этом принтере.", "✓ %@: Skalierung %@ %%. Gilt für alle Drucke auf diesem Drucker."),
"✓ %@ valide · scannable · les chiffres suivent les barres": ("✓ %@ valid · scannable · digits follow the bars", "✓ %@ корректен · читается · цифры соответствуют штрихам", "✓ %@ gültig · scannbar · Ziffern passen zu den Strichen"),
"✓ Textes lisibles, rien ne déborde, codes scannables.": ("✓ Texts readable, nothing overflows, codes scannable.", "✓ Тексты читаются, ничего не вылезает, коды читаются.", "✓ Texte lesbar, nichts läuft über, Codes scannbar."),
"Écrit": ("Written", "Написано", "Geschrieben"),
"Deutsch": ("Deutsch", "Deutsch", "Deutsch"),
"English": ("English", "English", "English"),
"Français": ("Français", "Français", "Français"),
"Timing": ("Timing", "Тайминг", "Timing"),
"Total": ("Total", "Итого", "Gesamt"),
"VU": ("VU", "VU", "VU"),
"Zoom": ("Zoom", "Масштаб", "Zoom"),
"mm": ("mm", "мм", "mm"),
"OK": ("OK", "OK", "OK"),
"PDF": ("PDF", "PDF", "PDF"),
"PNG 600 DPI": ("PNG 600 DPI", "PNG 600 DPI", "PNG 600 DPI"),
"US Letter": ("US Letter", "US Letter", "US Letter"),
"Client ID": ("Client ID", "Client ID", "Client ID"),
"NR": ("NR", "NR", "NR"),
"Spotify": ("Spotify", "Spotify", "Spotify"),
"LaFleurStudio": ("LaFleurStudio", "LaFleurStudio", "LaFleurStudio"),
"LAFLEURSTUDIO": ("LAFLEURSTUDIO", "LAFLEURSTUDIO", "LAFLEURSTUDIO"),
"Claude": ("Claude", "Claude", "Claude"),
"Custom ": ("Custom ", "Своя ", "Eigene "),
}
