# Noms des réglages (énumérations), panneaux, et textes ajoutés ensuite.
T = {
"Recto seul": ("Front only", "Только лицевая", "Nur Vorderseite"),
"Court": ("Short", "Короткий", "Kurz"),
"Normal": ("Normal", "Обычный", "Normal"),
"Long": ("Long", "Длинный", "Lang"),
"Biseauté": ("Tapered", "Скошенный", "Abgeschrägt"),
"Pochette de l'album": ("Album cover", "Обложка альбома", "Albumcover"),
"Collage des covers": ("Cover collage", "Коллаж обложек", "Cover-Collage"),
"Ta propre image": ("Your own image", "Твоё изображение", "Dein eigenes Bild"),
"Style « K7 maison »": ("Homemade-tape style", "Стиль «самодельная кассета»", "Selbstgemacht-Stil"),
"Design graphique de Claude": ("Graphic design by Claude", "Графический дизайн от Claude", "Grafikdesign von Claude"),
"Rabat, en bas": ("Flap, bottom", "Клапан, внизу", "Lasche, unten"),
"Volet intérieur": ("Inner panel", "Внутренняя панель", "Innenfeld"),
"Libre (à glisser)": ("Free (drag it)", "Свободно (перетащи)", "Frei (ziehen)"),
"Blanc": ("White", "Белый", "Weiß"),
"Design": ("Design", "Дизайн", "Design"),
"Perso": ("Custom", "Свой", "Eigene"),
"Lien Spotify": ("Spotify link", "Ссылка Spotify", "Spotify-Link"),
"Lien perso": ("Own link", "Своя ссылка", "Eigener Link"),
"Type I · Normal": ("Type I · Normal", "Тип I · Normal", "Typ I · Normal"),
"Type II · Chrome": ("Type II · Chrome", "Тип II · Chrome", "Typ II · Chrom"),
"Type IV · Métal": ("Type IV · Metal", "Тип IV · Metal", "Typ IV · Metall"),
"Aucun": ("None", "Нет", "Keine"),
"Dolby B": ("Dolby B", "Dolby B", "Dolby B"),
"Dolby C": ("Dolby C", "Dolby C", "Dolby C"),
"Rabat": ("Flap", "Клапан", "Lasche"),
"Intérieur": ("Inside", "Внутри", "Innen"),
"Patte de colle": ("Glue tab", "Клеевой клапан", "Klebelasche"),
"Fenêtre": ("Window", "Окно", "Fenster"),
"Hauteur": ("Height", "Высота", "Höhe"),
"recto verso, retourner sur le grand côté": ("double-sided, flip on the long edge", "двусторонняя, переворот по длинной стороне", "beidseitig, über die lange Kante wenden"),
"album": ("album", "альбом", "Album"),
"mixtape": ("mixtape", "микстейп", "Mixtape"),
"Usage perso uniquement": ("Personal use only", "Только для личного использования", "Nur für den privaten Gebrauch"),
"Les logos des maisons de disque sont des marques. Importe seulement un fichier que tu as déjà ; l'app ne télécharge ni ne partage jamais de logos.": ("Record label logos are trademarks. Only import a file you already have; the app never downloads or shares logos.", "Логотипы лейблов — товарные знаки. Импортируй только файл, который у тебя уже есть; приложение никогда не скачивает и не распространяет логотипы.", "Label-Logos sind Marken. Importiere nur eine Datei, die du schon hast; die App lädt oder teilt nie Logos."),
"Choisir le fichier…": ("Choose the file…", "Выбрать файл…", "Datei wählen…"),
"Importer un logo…": ("Import a logo…", "Импорт логотипа…", "Logo importieren…"),
"Retirer le logo": ("Remove the logo", "Убрать логотип", "Logo entfernen"),
"Sans logo importé, le nom est écrit en texte.": ("Without an imported logo, the name is written as text.", "Без импортированного логотипа название пишется текстом.", "Ohne importiertes Logo wird der Name als Text geschrieben."),
"Rotation": ("Rotation", "Поворот", "Drehung"),
"Glisse les codes dans l'aperçu de la J-card.": ("Drag the codes in the J-card preview.", "Перетащи коды в окне просмотра вкладыша.", "Zieh die Codes in der J-Card-Vorschau."),
}
