# Messages de la barre d'état.
T = {
"Prêt": ("Ready", "Готово", "Bereit"),
"Donne d'abord un titre à la cassette.": ("Give the tape a title first.", "Сначала дай кассете название.", "Gib der Kassette zuerst einen Titel."),
"Recherche des vraies éditions cassette de « %@ »…": ("Looking for real cassette editions of “%@”…", "Ищу настоящие кассетные издания «%@»…", "Suche echte Kassettenausgaben von „%@“…"),
"Aucune édition cassette trouvée : Claude partira de la pochette.": ("No cassette edition found: Claude will start from the cover.", "Кассетных изданий не найдено: Claude начнёт с обложки.", "Keine Kassettenausgabe gefunden: Claude startet mit dem Cover."),
"Éditions cassette trouvées : %lld": ("Cassette editions found: %lld", "Найдено кассетных изданий: %lld", "Gefundene Kassettenausgaben: %lld"),
"Recherche des vraies éditions cassette…": ("Looking for real cassette editions…", "Ищу настоящие кассетные издания…", "Suche echte Kassettenausgaben…"),
"Claude prépare le design…": ("Claude is preparing the design…", "Claude готовит дизайн…", "Claude bereitet das Design vor…"),
"Claude refait la variante %@…": ("Claude is redoing variant %@…", "Claude переделывает вариант %@…", "Claude macht Variante %@ neu…"),
"Claude a proposé %lld variantes": ("Claude proposed %lld variants", "Claude предложил вариантов: %lld", "Claude hat %lld Varianten vorgeschlagen"),
"La recherche web de Claude est désactivée (Réglages → Claude).": ("Claude's web search is turned off (Settings → Claude).", "Поиск Claude в интернете выключен (Настройки → Claude).", "Claudes Websuche ist aus (Einstellungen → Claude)."),
"Claude cherche les infos de l'album sur le web…": ("Claude is looking up the album on the web…", "Claude ищет данные альбома в интернете…", "Claude sucht Albuminfos im Web…"),
"Infos de l'album mises à jour": ("Album info updated", "Данные альбома обновлены", "Albuminfos aktualisiert"),
"Tout est corrigé ✓": ("All fixed ✓", "Всё исправлено ✓", "Alles korrigiert ✓"),
"Alertes à régler à la main : %lld": ("Alerts to fix by hand: %lld", "Предупреждений исправить вручную: %lld", "Von Hand zu lösende Warnungen: %lld"),
"Claude regarde la jaquette…": ("Claude is looking at the J-card…", "Claude смотрит на вкладыш…", "Claude schaut sich die J-Card an…"),
"Vérification de Claude : tout est bon ✓": ("Claude's check: all good ✓", "Проверка Claude: всё в порядке ✓", "Claudes Prüfung: alles gut ✓"),
"Corrections proposées par Claude : %lld": ("Fixes proposed by Claude: %lld", "Исправлений от Claude: %lld", "Korrekturen von Claude: %lld"),
"PDF enregistré (fond perdu, traits de coupe et de pliage)": ("PDF saved (bleed, crop and fold marks)", "PDF сохранён (вылеты, метки реза и сгиба)", "PDF gespeichert (Beschnitt, Schnitt- und Falzmarken)"),
"%lld images PNG 600 DPI enregistrées": ("%lld PNG 600 DPI images saved", "Сохранено изображений PNG 600 DPI: %lld", "%lld PNG-Bilder mit 600 DPI gespeichert"),
"%lld image PNG 600 DPI enregistrée": ("%lld PNG 600 DPI image saved", "Сохранено изображений PNG 600 DPI: %lld", "%lld PNG-Bild mit 600 DPI gespeichert"),
"Image ajoutée au recto": ("Image added to the front", "Изображение добавлено на лицевую сторону", "Bild auf der Vorderseite eingefügt"),
"Logo importé (usage perso uniquement)": ("Logo imported (personal use only)", "Логотип импортирован (только для личного использования)", "Logo importiert (nur privat)"),
"Aucune police lisible dans ces fichiers": ("No readable font in these files", "В этих файлах нет читаемых шрифтов", "Keine lesbare Schrift in diesen Dateien"),
"Police importée : %@": ("Font imported: %@", "Шрифт импортирован: %@", "Schrift importiert: %@"),
"Connexion à Spotify dans ton navigateur…": ("Connecting to Spotify in your browser…", "Подключение к Spotify в браузере…", "Verbinde mit Spotify im Browser…"),
"Spotify connecté ✓": ("Spotify connected ✓", "Spotify подключён ✓", "Spotify verbunden ✓"),
"Recherche sur Spotify…": ("Searching Spotify…", "Поиск в Spotify…", "Suche auf Spotify…"),
"Rien trouvé": ("Nothing found", "Ничего не найдено", "Nichts gefunden"),
"Albums trouvés : %lld": ("Albums found: %lld", "Найдено альбомов: %lld", "Gefundene Alben: %lld"),
"Chargement de tes playlists…": ("Loading your playlists…", "Загрузка плейлистов…", "Lade deine Playlists…"),
"Import de « %@ »…": ("Importing “%@”…", "Импорт «%@»…", "Importiere „%@“…"),
"Import du lien Spotify…": ("Importing the Spotify link…", "Импорт ссылки Spotify…", "Importiere den Spotify-Link…"),
"Recherche sur MusicBrainz…": ("Searching MusicBrainz…", "Поиск в MusicBrainz…", "Suche auf MusicBrainz…"),
"Rien trouvé sur MusicBrainz (les petits artistes n'y sont pas toujours)": ("Nothing found on MusicBrainz (small artists aren't always there)", "На MusicBrainz ничего нет (небольших артистов там бывает нет)", "Nichts auf MusicBrainz gefunden (kleine Künstler fehlen dort manchmal)"),
"Éditions trouvées : %lld": ("Editions found: %lld", "Найдено изданий: %lld", "Gefundene Ausgaben: %lld"),
"Import de « %@ » depuis MusicBrainz…": ("Importing “%@” from MusicBrainz…", "Импорт «%@» из MusicBrainz…", "Importiere „%@“ von MusicBrainz…"),
"Lecture du dossier audio…": ("Reading the audio folder…", "Чтение папки с аудио…", "Lese den Audio-Ordner…"),
"Lecture du dossier…": ("Reading the folder…", "Чтение папки…", "Lese den Ordner…"),
"Aucun fichier audio dans ce dossier": ("No audio file in this folder", "В этой папке нет аудиофайлов", "Keine Audiodatei in diesem Ordner"),
"Aucun fichier audio dans le dossier": ("No audio file in the folder", "В папке нет аудиофайлов", "Keine Audiodatei im Ordner"),
"Choisis ton dossier audio": ("Choose your audio folder", "Выбери папку с аудио", "Wähle deinen Audio-Ordner"),
"%lld fichiers chargés dans l'ordre des pistes": ("%lld files loaded in track order", "Загружено файлов по порядку треков: %lld", "%lld Dateien in Titelreihenfolge geladen"),
"%lld / %lld morceaux associés à un fichier": ("%lld / %lld tracks linked to a file", "%lld / %lld треков привязаны к файлу", "%lld / %lld Titel mit einer Datei verknüpft"),
"%lld / %lld morceaux associés à un fichier · %lld à confirmer": ("%lld / %lld tracks linked to a file · %lld to confirm", "%lld / %lld треков привязаны к файлу · подтвердить: %lld", "%lld / %lld Titel mit einer Datei verknüpft · %lld zu bestätigen"),
"« %@ » retiré de la cassette (il ne sera pas enregistré)": ("“%@” removed from the tape (it won't be recorded)", "«%@» убран с кассеты (не будет записан)", "„%@“ von der Kassette entfernt (wird nicht aufgenommen)"),
"« %@ » remis à sa place": ("“%@” put back", "«%@» возвращён на место", "„%@“ zurückgelegt"),
"Claude répartit les faces…": ("Claude is splitting the sides…", "Claude распределяет стороны…", "Claude verteilt die Seiten…"),
"Faces réparties par Claude ✓": ("Sides split by Claude ✓", "Стороны распределены Claude ✓", "Seiten von Claude verteilt ✓"),
"Claude compose la sélection…": ("Claude is composing the selection…", "Claude собирает подборку…", "Claude stellt die Auswahl zusammen…"),
"Recherche des titres sur Spotify…": ("Looking up the tracks on Spotify…", "Поиск треков в Spotify…", "Suche die Titel auf Spotify…"),
"%lld titres trouvés : coche ceux que tu gardes": ("%lld tracks found: tick the ones you keep", "Найдено треков: %lld — отметь, что оставить", "%lld Titel gefunden: hake die an, die du behältst"),
}
