# Alertes, erreurs, platine.
T = {
"« %@ » dépasse de la zone %@ de %@ mm.": ("“%@” overflows the %@ area by %@ mm.", "«%@» выходит за зону «%@» на %@ мм.", "„%@“ ragt %@ mm über den Bereich %@ hinaus."),
"Le texte de la zone %@ est trop haut : il sort de %@ mm.": ("The %@ text is too tall: it sticks out by %@ mm.", "Текст зоны «%@» слишком высокий: выходит на %@ мм.", "Der Text im Bereich %@ ist zu hoch: er ragt %@ mm hinaus."),
"Texte de la zone %@ en %@ pt : illisible une fois imprimé (5 pt minimum).": ("%@ text at %@ pt: unreadable once printed (5 pt minimum).", "Текст зоны «%@» размером %@ pt: не читается после печати (минимум 5 pt).", "Text im Bereich %@ mit %@ pt: gedruckt unlesbar (mindestens 5 pt)."),
"Contraste faible dans la zone %@ (%@:1) : le texte se lira mal.": ("Low contrast in the %@ area (%@:1): hard to read.", "Слабый контраст в зоне «%@» (%@:1): текст будет плохо читаться.", "Schwacher Kontrast im Bereich %@ (%@:1): schlecht lesbar."),
"%@ : barres plus claires que le fond, la plupart des lecteurs ne le liront pas.": ("%@: bars lighter than the background, most scanners won't read it.", "%@: штрихи светлее фона, большинство сканеров его не прочтут.", "%@: Striche heller als der Hintergrund, die meisten Scanner lesen das nicht."),
"%@ : contraste trop faible entre les barres et le fond (%@:1).": ("%@: contrast between bars and background too low (%@:1).", "%@: слишком слабый контраст между штрихами и фоном (%@:1).", "%@: Kontrast zwischen Strichen und Hintergrund zu schwach (%@:1)."),
"%@ très petit (module de %@ mm) : il risque de ne pas se scanner.": ("%@ very small (%@ mm module): it may not scan.", "%@ очень мелкий (модуль %@ мм): может не считаться.", "%@ sehr klein (Modul %@ mm): wird eventuell nicht gescannt."),
"tranche": ("spine", "корешок", "Rücken"),
"titre": ("title", "название", "Titel"),
"artiste": ("artist", "исполнитель", "Künstler"),
"badge de bande": ("tape badge", "значок ленты", "Band-Plakette"),
"texte du code-barres": ("barcode text", "текст штрихкода", "Strichcode-Text"),
"ligne ℗/©": ("℗/© line", "строка ℗/©", "℗/©-Zeile"),
"tracklist": ("tracklist", "треклист", "Tracklist"),
"notes": ("notes", "заметки", "Notizen"),
"crédits": ("credits", "титры", "Credits"),
"étiquette": ("label", "этикетка", "Etikett"),
"obi": ("obi", "оби", "Obi"),
"Numéro « %@ » impossible en Code 128 : caractères ASCII seulement.": ("Number “%@” not possible in Code 128: ASCII characters only.", "Номер «%@» невозможен в Code 128: только символы ASCII.", "Nummer „%@“ in Code 128 nicht möglich: nur ASCII-Zeichen."),
"Numéro « %@ » impossible en %@ : chiffres seulement, 12 ou 13 pour l'EAN, 11 ou 12 pour l'UPC.": ("Number “%@” not possible in %@: digits only, 12 or 13 for EAN, 11 or 12 for UPC.", "Номер «%@» невозможен в %@: только цифры, 12 или 13 для EAN, 11 или 12 для UPC.", "Nummer „%@“ in %@ nicht möglich: nur Ziffern, 12 oder 13 für EAN, 11 oder 12 für UPC."),
"QR code : pas de lien Spotify pour cette cassette. Choisis « Lien perso » ou « Texte ».": ("QR code: no Spotify link for this tape. Choose “Own link” or “Text”.", "QR-код: у этой кассеты нет ссылки Spotify. Выбери «Своя ссылка» или «Текст».", "QR-Code: kein Spotify-Link für diese Kassette. Wähle „Eigener Link“ oder „Text“."),
"QR code vide : écris le lien ou le texte.": ("Empty QR code: type the link or text.", "Пустой QR-код: введи ссылку или текст.", "Leerer QR-Code: gib den Link oder Text ein."),
"Code Spotify : cette cassette n'a pas été importée depuis Spotify.": ("Spotify code: this tape wasn't imported from Spotify.", "Код Spotify: эта кассета не импортирована из Spotify.", "Spotify-Code: diese Kassette wurde nicht aus Spotify importiert."),
"GAUCHE": ("LEFT", "ЛЕВЫЙ", "LINKS"),
"DROITE": ("RIGHT", "ПРАВЫЙ", "RECHTS"),
"BLANC DE DÉBUT DE BANDE": ("LEADER SILENCE", "ТИШИНА В НАЧАЛЕ", "STILLE AM BANDANFANG"),
"BLANC ENTRE LES MORCEAUX": ("SILENCE BETWEEN TRACKS", "ТИШИНА МЕЖДУ ТРЕКАМИ", "STILLE ZWISCHEN TITELN"),
"BOUT DE BANDE DANS %@": ("END OF TAPE IN %@", "КОНЕЦ ЛЕНТЫ ЧЕРЕЗ %@", "BANDENDE IN %@"),
"INVERSION DE LA PLATINE…": ("DECK REVERSING…", "РЕВЕРС ДЕКИ…", "DECK WENDET…"),
"RELÂCHE LA PAUSE… %lld": ("RELEASE PAUSE… %lld", "ОТПУСТИ ПАУЗУ… %lld", "PAUSE LÖSEN… %lld"),
"FACE %@ TERMINÉE": ("SIDE %@ DONE", "СТОРОНА %@ ГОТОВА", "SEITE %@ FERTIG"),
"PRÊT · %lld MORCEAUX": ("READY · %lld TRACKS", "ГОТОВО · ТРЕКОВ: %lld", "BEREIT · %lld TITEL"),
"Aucun dossier": ("No folder", "Папка не выбрана", "Kein Ordner"),
"Pas de fichier audio pour « %@ ». Associe-le dans l'écran Mixtape.": ("No audio file for “%@”. Link it in the Mixtape screen.", "Нет аудиофайла для «%@». Привяжи его на экране Микстейп.", "Keine Audiodatei für „%@“. Ordne sie im Mixtape-Bildschirm zu."),
"Impossible d'utiliser cette sortie audio.": ("Can't use this audio output.", "Не удаётся использовать этот аудиовыход.", "Dieser Audioausgang kann nicht verwendet werden."),
"Claude a répondu %lld : %@": ("Claude replied %lld: %@", "Claude ответил %lld: %@", "Claude antwortete %lld: %@"),
"Claude a refusé la demande (%@).": ("Claude declined the request (%@).", "Claude отклонил запрос (%@).", "Claude hat die Anfrage abgelehnt (%@)."),
"Réponse de Claude vide ou illisible.": ("Claude's reply was empty or unreadable.", "Ответ Claude пустой или нечитаемый.", "Claudes Antwort war leer oder unlesbar."),
"Réponse de Claude coupée (trop longue).": ("Claude's reply was cut off (too long).", "Ответ Claude обрезан (слишком длинный).", "Claudes Antwort wurde abgeschnitten (zu lang)."),
"Ajoute ton jeton Discogs dans Réglages → Sources.": ("Add your Discogs token in Settings → Sources.", "Добавь токен Discogs в Настройки → Источники.", "Füge dein Discogs-Token unter Einstellungen → Quellen hinzu."),
"Jeton Discogs refusé : vérifie-le dans Réglages → Sources.": ("Discogs token rejected: check it in Settings → Sources.", "Токен Discogs отклонён: проверь его в Настройки → Источники.", "Discogs-Token abgelehnt: prüfe es unter Einstellungen → Quellen."),
"Discogs a répondu %lld. Réessaie dans un instant.": ("Discogs replied %lld. Try again in a moment.", "Discogs ответил %lld. Попробуй чуть позже.", "Discogs antwortete %lld. Versuch es gleich nochmal."),
"MusicBrainz a répondu %lld. Réessaie dans un instant.": ("MusicBrainz replied %lld. Try again in a moment.", "MusicBrainz ответил %lld. Попробуй чуть позже.", "MusicBrainz antwortete %lld. Versuch es gleich nochmal."),
"Pas connecté à Spotify (Réglages → Spotify).": ("Not connected to Spotify (Settings → Spotify).", "Нет подключения к Spotify (Настройки → Spotify).", "Nicht mit Spotify verbunden (Einstellungen → Spotify)."),
"Spotify a répondu %lld : %@": ("Spotify replied %lld: %@", "Spotify ответил %lld: %@", "Spotify antwortete %lld: %@"),
"Lien non reconnu : colle un lien Spotify de playlist, d'album ou de morceau.": ("Link not recognised: paste a Spotify playlist, album or track link.", "Ссылка не распознана: вставь ссылку Spotify на плейлист, альбом или трек.", "Link nicht erkannt: füge einen Spotify-Link zu Playlist, Album oder Titel ein."),
"Spotify refuse l'accès : son API demande un compte Premium. Sans Premium, utilise « Cassette depuis le dossier ».": ("Spotify refuses access: its API requires a Premium account. Without Premium, use “Tape from folder”.", "Spotify отказывает в доступе: API требует Premium. Без Premium используй «Кассета из папки».", "Spotify verweigert den Zugriff: die API braucht ein Premium-Konto. Ohne Premium nutze „Kassette aus Ordner“."),
"Sources": ("Sources", "Источники", "Quellen"),
"Impression": ("Printing", "Печать", "Drucken"),
"Audio": ("Audio", "Аудио", "Audio"),
"Platine": ("Deck", "Дека", "Deck"),
"Langue": ("Language", "Язык", "Sprache"),
"Conditions": ("Terms", "Условия", "Bedingungen"),
"Paroles : genius.com": ("Lyrics: genius.com", "Тексты песен: genius.com", "Songtexte: genius.com"),
"Lien vers les paroles (genius.com)": ("Link to the lyrics (genius.com)", "Ссылка на тексты песен (genius.com)", "Link zu den Songtexten (genius.com)"),
"Jamais les paroles complètes (droits d'auteur) : seulement où les trouver.": ("Never the full lyrics (copyright): only where to find them.", "Никогда полный текст (авторские права): только где его найти.", "Nie die vollständigen Songtexte (Urheberrecht): nur wo man sie findet."),
"Reprendre crédits et notes": ("Use these credits and notes", "Взять титры и заметки", "Credits und Notizen übernehmen"),
"Glisse les codes où tu veux": ("Drag the codes wherever you like", "Перетащи коды куда хочешь", "Zieh die Codes, wohin du willst"),
"Orientation": ("Orientation", "Ориентация", "Ausrichtung"),
"Vertical": ("Portrait", "Вертикально", "Hochformat"),
"Paysage": ("Landscape", "Горизонтально", "Querformat"),
"Modifications de Claude appliquées ✓": ("Claude's changes applied ✓", "Изменения Claude применены ✓", "Änderungen von Claude übernommen ✓"),
"Image posée : %@": ("Image placed: %@", "Изображение добавлено: %@", "Bild platziert: %@"),
"Aucune image trouvée pour « %@ ». Importe-la toi-même ou reformule.": ("No image found for “%@”. Import it yourself or rephrase.", "Не найдено изображение для «%@». Импортируй сам или переформулируй.", "Kein Bild für „%@“ gefunden. Importiere es selbst oder formuliere um."),
"Retirer cette image": ("Remove this image", "Убрать это изображение", "Dieses Bild entfernen"),
}
